//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace CSharpClient.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MedRecWebServicesSoapBinding", Namespace="http://www.bea.com/medrec")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseVO))]
    public class MedRecWebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public MedRecWebServices() {
            this.Url = "http://localhost:7001/ws_medrec/MedRecWebServices";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bea.com/medrecfindPatientByLastNameWild", RequestNamespace="http://www.bea.com/medrec", ResponseNamespace="http://www.bea.com/medrec", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        public Patient[] findPatientByLastNameWild(string pLastname) {
            object[] results = this.Invoke("findPatientByLastNameWild", new object[] {
                        pLastname});
            return ((Patient[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindPatientByLastNameWild(string pLastname, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findPatientByLastNameWild", new object[] {
                        pLastname}, callback, asyncState);
        }
        
        /// <remarks/>
        public Patient[] EndfindPatientByLastNameWild(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Patient[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bea.com/medrecgetRecord", RequestNamespace="http://www.bea.com/medrec", ResponseNamespace="http://www.bea.com/medrec", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public Record getRecord(int pRecordId) {
            object[] results = this.Invoke("getRecord", new object[] {
                        pRecordId});
            return ((Record)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRecord(int pRecordId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRecord", new object[] {
                        pRecordId}, callback, asyncState);
        }
        
        /// <remarks/>
        public Record EndgetRecord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Record)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bea.com/medrecfindPatientBySsn", RequestNamespace="http://www.bea.com/medrec", ResponseNamespace="http://www.bea.com/medrec", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public Patient findPatientBySsn(string pPatientSSN) {
            object[] results = this.Invoke("findPatientBySsn", new object[] {
                        pPatientSSN});
            return ((Patient)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindPatientBySsn(string pPatientSSN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findPatientBySsn", new object[] {
                        pPatientSSN}, callback, asyncState);
        }
        
        /// <remarks/>
        public Patient EndfindPatientBySsn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Patient)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bea.com/medrecgetRecordsSummary", RequestNamespace="http://www.bea.com/medrec", ResponseNamespace="http://www.bea.com/medrec", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public RecordsSummary getRecordsSummary(int pPatientId) {
            object[] results = this.Invoke("getRecordsSummary", new object[] {
                        pPatientId});
            return ((RecordsSummary)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRecordsSummary(int pPatientId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRecordsSummary", new object[] {
                        pPatientId}, callback, asyncState);
        }
        
        /// <remarks/>
        public RecordsSummary EndgetRecordsSummary(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RecordsSummary)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bea.com/medrecupdatePatient", RequestNamespace="http://www.bea.com/medrec", ResponseNamespace="http://www.bea.com/medrec", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public Patient updatePatient(Patient pPatientVO) {
            object[] results = this.Invoke("updatePatient", new object[] {
                        pPatientVO});
            return ((Patient)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdatePatient(Patient pPatientVO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updatePatient", new object[] {
                        pPatientVO}, callback, asyncState);
        }
        
        /// <remarks/>
        public Patient EndupdatePatient(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Patient)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.bea.medrec.value")]
    public class Patient : BaseVO {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MiddleName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName;
        
        /// <remarks/>
        public System.DateTime DateOfBirth;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ssn;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address Address;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.bea.medrec.value")]
    public class Address : BaseVO {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetName1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetName2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string State;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZipCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.bea.medrec.value")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Patient))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Prescription))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VitalSigns))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Physician))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Record))]
    public class BaseVO {
        
        /// <remarks/>
        public int Id;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.bea.medrec.value")]
    public class RecordsSummary {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Records", IsNullable=true)]
        public Record[] Records;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Prescriptions", IsNullable=true)]
        public Prescription[] Prescriptions;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.bea.medrec.value")]
    public class Record : BaseVO {
        
        /// <remarks/>
        public int PatientId;
        
        /// <remarks/>
        public System.DateTime Date;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Symptoms;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Diagnosis;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Notes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Physician Physician;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VitalSigns VitalSigns;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Prescriptions", IsNullable=true)]
        public Prescription[] Prescriptions;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.bea.medrec.value")]
    public class Physician : BaseVO {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MiddleName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.bea.medrec.value")]
    public class VitalSigns : BaseVO {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Temperature;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BloodPressure;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Pulse;
        
        /// <remarks/>
        public int Weight;
        
        /// <remarks/>
        public int Height;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:com.bea.medrec.value")]
    public class Prescription : BaseVO {
        
        /// <remarks/>
        public int PatientId;
        
        /// <remarks/>
        public int RecordId;
        
        /// <remarks/>
        public System.DateTime DatePrescribed;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Drug;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Dosage;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Frequency;
        
        /// <remarks/>
        public int RefillsRemaining;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Instructions;
    }
}
